export const BEGIN_REQUEST = "BEGIN_REQUEST";
export const REQUEST_ERROR = "REQUEST_ERROR";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";

