export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST";
export const GET_PRODUCTS_ERROR = "GET_PRODUCTS_ERROR";


export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const GET_PRODUCT_REQUEST = "GET_PRODUCT_REQUEST";
export const GET_PRODUCT_ERROR = "GET_PRODUCT_ERROR";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN SUCCESS";
export const LOGIN_FAILED = "LOGIN FAILED";
export const LOGIN_ERROR = "LOGIN ERROR";

export const LOGOUT = "LOGOUT"

export const UPDATE_SEARCH = "UPDATE_SEARCH";
export const UPDATE_SORT="UPDATE_SORT"

export const TOGGLE_CART_HIDDEN= "TOGGLE_CART_HIDDEN";
export const ADD_ITEM= "ADD_ITEM";
export const REMOVE_ITEM="REMOVE ITEM";
export const CLEAR_ITEM_FROM_CART="CLEAR ITEM FROM CART";

